version: 0.5.3
# Modulator plugin configuration file

# Languages: ES, EN
language: ES

# ItemChat settings
itemchat:
  # Enable and disable itemchat module
  enable: true
  # All item can be shown in chat
  norestriction: true
  # Use Vault economy Api
  usevault: true
  # Price to set item owner
  priceowner: 500