version: 0.5.1
# Modulator plugin configuration file

# Languages: ES, EN
language: ES

# Zanakik settings
zanakik:
  # Enable and disable zanakik module
  enable: true
  # Only console can zkik a player
  noplayerzkik: true
  # All players are zanakikeable
  ignorebypass: false